# Generated by Django 5.1 on 2024-10-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_company_employees_alter_employee_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='iqama',
            name='renewfor',
            field=models.SmallIntegerField(default=3),
        ),
    ]
